CREATE DATABASE IF NOT EXISTS nathan_macdiarmid_lab05;
USE nathan_macdiarmid_lab05;

-- Q1 --

CREATE TABLE IF NOT EXISTS STUDENT_INFO (
    ID INTEGER(10) PRIMARY KEY,
    NAME VARCHAR(100),
    DOB DATE,
    INCOME DECIMAL(10,2),
    COURSE_ID INTEGER(5)
);

-- Q2 --

CREATE TABLE IF NOT EXISTS COURSE_INFO (
    ID INTEGER(10) PRIMARY KEY,
    NAME VARCHAR(100),
    LOCATION VARCHAR(200),
    STARTDATE DATE,
    TYPE VARCHAR(100)
);

 -- Q3 --

ALTER TABLE STUDENT_INFO ADD IF NOT EXISTS ADDRESS VARCHAR(200) DEFAULT NULL;

-- Q4 --

ALTER TABLE STUDENT_INFO MODIFY COLUMN NAME VARCHAR(200);

-- Q5 --

RENAME TABLE STUDENT_INFO TO STUDENT;

-- Q6 --

RENAME TABLE COURSE_INFO TO COURSE;

-- Q7 --

INSERT INTO STUDENT VALUES (1, 'JOHN', '1998-05-01', 1200, 100, 'NORTH');
INSERT INTO STUDENT VALUES (2, 'MIKE', '2000-08-15', 1100.15, 200, 'WEST');
INSERT INTO STUDENT VALUES (3, 'SAM', '1997-11-01', 500, 100, 'SOUTH');

-- Q8 --

INSERT INTO COURSE VALUES (100, 'Fundamentals of Web Development', 'Azrieli Pavilion', '2023-09-10', 'mandatory');
INSERT INTO COURSE VALUES (300, 'Analytical Methods', 'Tory Building', '2023-09-17', 'elevtive');
INSERT INTO COURSE VALUES (500, 'Java Programming', 'Tory Building', '2023-09-17', 'elective');
INSERT INTO COURSE VALUES (700, 'C++ Programming', 'Patterson Hall', '2023-09-10', 'elective');

-- Q9 --

UPDATE STUDENT SET INCOME = 1000 WHERE ID = 2;

-- Q11 --

DELETE FROM STUDENT WHERE ID = 2;

-- Q13 --

SELECT * FROM STUDENT;

-- Q15 --

SELECT NAME, DOB, INCOME FROM STUDENT;

-- Q17 --

SELECT ID, NAME, DOB, INCOME FROM STUDENT WHERE INCOME > 600;

-- Q19 --

SELECT STUDENT.ID, STUDENT.NAME, STUDENT.DOB, COURSE.NAME AS COURSENAME FROM STUDENT JOIN COURSE ON STUDENT.COURSE_ID = COURSE.ID;

-- Q21 --

TRUNCATE TABLE STUDENT;

-- Q22 --

TRUNCATE TABLE COURSE;

-- Q23 --

DROP TABLE STUDENT;
SELECT * FROM STUDENT;

-- Q24 --

DROP TABLE COURSE;
SELECT * FROM COURSE;

-- PART IV Q3 --

CREATE TABLE game_details (
    game_ID INT(10) AUTO_INCREMENT PRIMARY KEY,
    game_name VARCHAR(100),
    release_date DATE,
    game_price DECIMAL(10,2),
    game_description TEXT
);